spring:
  main:
    web-application-type: reactive
  r2dbc:
    username: piotr
    password: password
    name: maply
    url: r2dbc:mysql://localhost:3306
  data:
    r2dbc:
      repositories:
        enabled: true

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"